package com.java.api.vegetable_supply.mapper;

import org.springframework.stereotype.Component;

import com.java.api.vegetable_supply.dto.VegetableDTO;
import com.java.api.vegetable_supply.entity.Vegetable;

@Component
public class VegetableMapper {
	
	// Convert DTO -> Entity (Saving data to DB)
	public Vegetable toEntity(VegetableDTO dto) {
        Vegetable vegetable = new Vegetable();
        // ID is usually generated by DB, so we might skip setting it for new items
        if(dto.getVegetableId() != null) {
            vegetable.setVegetableId(dto.getVegetableId());
        }
        vegetable.setVegetableName(dto.getVegetableName());
        vegetable.setPricePerKg(dto.getPricePerKg());
        vegetable.setLastRestocked(dto.getLastRestocked());
        vegetable.setStockQuantity(dto.getStockQuantity());
        vegetable.setSupplierName(dto.getSupplierName());
        vegetable.setCategory(dto.getCategory());

        return vegetable;
    }

    // Convert Entity -> DTO (Sending data to user)
    public VegetableDTO toDTO(Vegetable vegetable) {
    	if (vegetable == null) {
            return null;
        }
        VegetableDTO dto = new VegetableDTO();
        dto.setVegetableId(vegetable.getVegetableId());
        dto.setVegetableName(vegetable.getVegetableName());
        dto.setPricePerKg(vegetable.getPricePerKg());
        dto.setSupplierName(vegetable.getSupplierName());
        dto.setStockQuantity(vegetable.getStockQuantity());
        dto.setLastRestocked(vegetable.getLastRestocked());
        dto.setCategory(vegetable.getCategory());

        return dto;
    }

    
    
}
